sudo: false
language: c
cache: ccache
script:
#
# Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
#

#
# Toolchain Choice
# This will clone TeamVee Prebuilt Toolchains in directory described in build.sh
#
# Branchs available is:
# Google Branch is "google_gcc" | (1) 4.7 / (2) 4.8
# Linaro Branch is "linaro_gcc" | (1) 4.8.4 / (2) 4.9.4

# Toolchain branch select here is Google 4.7
- export ntoolchainbranch="google_gcc"
- git clone -b "${ntoolchainbranch}" "https://github.com/TeamVee/android_prebuilt_toolchains" "../android_prebuilt_toolchains"

# ${ntoolchainchoice} is your Toolchain Choice
- export ntoolchainchoice="1"

# ${ntoolchain}
# "4" is "Toolchain Choice"
- ntoolchain="4${ntoolchainchoice}"

# ${ndevice}
# "2" is "Clean Kernel"
# "3" is "Device Choice"
- ndevice="23"

# ${ndevicechoice} is "Number of Choice under Device Choice"
# - export ndevicechoice="#"

# ${nbuild}
# "6" is "Build Kernel"
# "7" is "Zip the kernel and Modules"
# "q" is to Exit of Script
- nbuild="67q"

# Main variables
# Call of 'build.sh'
# - source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"

# Export of zipfile to deploy
# - export zipfile#="${zipfile}"

# Sony Xperia E1 (Single/Dual/DTV) | D2004 D2005 D2104 D2015 D2114
- export ndevicechoice="1"

# TravisCI Custom Patches
- patch -p1 < zip-creator/travis-ci/0001-TravisCI-Custom-Patches.patch

# Build kernel with build.sh
- source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: nmbKfbMc6eLQwshzKWo857wxtI+QgLq0APpm6qLh1wcu2hGA8f6wexWhpWxUv1gRlwBAjojPEmXAlIybffhDMM/sQ6+FQGcYTO7tz/VBiszaGC0rtOuFSWIFK8nm2HfrwSgGdWlFLI8xwSYBciX/7qYo/7BibfWQPUqgbf8OXiEgBv3BxNW0WokRApqv3qMq2VLqJzJsfkDYFrBD4viOY2UY8uJMYwefNJnj5Mi/64NrSSFrT188lZu8/a+pPRA9esMlLz0uF+xZqiH/FX4Rg70o/16iRqdz2R1G5XGA1whHa0von0ZnkzY1+Sv92KjK2T6T9b00Oqm3Px9IjMBaQjalOtqKaSnKAz9Vdgw/aqdT26sg/U6REuj7WLK2hikX1SHuxBYiFDIDlIfmBRGU37qJI9+j6qFgDIt42YKy6WYisHN3KraOLIvT38kNaiXWkQe6QuuQ4Y1DlcYK5BbL3MQHWQ1Z7BYst+2iY6UkhVA5jFS+MpIP1VoiS7W/yFmkFPYbGAML4S+FU0JLv7Ek+Ltq9vtd0byDaN6CCQiWY6qTIWZx/LNLMYkBE1ILr2FN2pktkNZk3kDVl6bawJUEjw2xoOSJlBNLhh2/Nm2WHPV2Rvx7+QSlN7h9FW6CR9/03T287Rm2+5LyxILSjtwHGIOw2fSn2BLHeZzLSnknUW4=
  file:
    - "zip-creator/${zipfile}"
  on:
    tags: true
